### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by fanil30** [Doge-is-Dope/Kotlin-WalletConnectV2-Sample#1]
Unable to locate secret.properties in build.gradle

        def secretPropertiesFile = rootProject.file("secret.properties")
        def secretProperties = new Properties()
        secretProperties.load(new FileInputStream(secretPropertiesFile))
        buildConfigField("String", "PROJECT_ID", secretProperties['WALLETCONNECT_PROJECT_ID'])

How to Handle that?

**Comment by Doge-is-Dope** [comment]
Hi,
You can create a file `secret.properties` in the root project directory. In the file, add your WalletConnect project ID which can be created from [WalletConnect Cloud](https://cloud.walletconnect.com/sign-in).
```
WALLETCONNECT_PROJECT_ID="YOUR_PROJECT_ID"
```
